name: Selenium Tests with Extent Reports

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Maven
        uses: actions/setup-maven@v3 # Use the official actions/setup-maven action
        with:
          maven-version: '3.9.1'

      - name: Build and Test
        run: |
          mvn clean install test

      - name: Generate Extent Reports
        run: |
          mkdir -p reports/extentreports
          cp target/surefire-reports/*.xml reports/extentreports/
          java -jar dependencies/extentreports-batch/extentreports-batch-6.10.0.jar -f html -o reports/extentreports/index.html

      - name: Upload Artifacts (using the latest version)
        uses: actions/upload-artifact@v3
        with:
          name: Extent Reports
          path: reports/extentreports

      - name: Publish HTML report
        uses: actions/github-script@v6
        with:
          script: |
            github.context.payload.outputs = {
              'report_url': 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ github.job }}/Extent%20Reports/index.html'
            }