## This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
#
## This workflow uses actions that are not certified by GitHub.
## They are provided by a third-party and are governed by
## separate terms of service, privacy policy, and support
## documentation.
#
#name: ExtentReport Workflow
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#
#      - name: Run test
#        run: mvn clean test
#
#      - name: Deploy pages
#        uses: JamesIves/github-pages-deploy-action@v4.5.0
#        with:
#          branch: gh-pages
#          folder: ./reports

name: ExtentReport Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
#      - name: Set up Native Selenium Grid with one hub and four Chrome nodes
#        run: docker-compose -f src/main/resources/docker-compose_selenium4.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d
#      - name: Check running containers
#        run: docker ps
      - name: Run tests - Chrome Headless
        continue-on-error: true
        run: mvn test -Dtest="restfulbooker.tests.**,google.tests.**,phptravels.tests.**" -Dexecution.type="Remote"
      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Check files in the allure-maven-plugin folder
        run: ls target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: "target/site/allure-maven-plugin"
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: Extent Report
          path: "ExtentReports.html"