name: MacRunSafari

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify your Java version
        distribution: 'adopt'

    - name: Install SafariDriver
      run: |
        sudo safaridriver --enable

    - name: Install AdBlock extension for Safari
      run: |
        # Create a directory for Safari extensions (if it doesn't already exist)
        mkdir -p ~/Library/Safari/Extensions

        # Download AdBlock .safariextz extension (direct download from GitHub release)
        curl -L -o ~/Library/Safari/Extensions/AdBlock.safariextz https://github.com/adblockplus/adblockpluschrome/releases/download/3.11.1/adblockplus-3.11.1.safariextz

        # Enable the extension in Safari (this may require Safari to be open)
        osascript -e 'tell application "Safari" to activate'
        osascript -e 'tell application "Safari" to open location "safari-extension://com.adblockplus.AdblockPlus.safariextz"'


    - name: Build with Maven
      run: mvn clean install  # Use `gradle build` if you are using Gradle

    - name: Run Tests
      run: mvn test  # Use `gradle test` if you are using Gradle
