## This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
#
## This workflow uses actions that are not certified by GitHub.
## They are provided by a third-party and are governed by
## separate terms of service, privacy policy, and support
## documentation.
#
#name: ExtentReport Workflow
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#
#      - name: Run test
#        run: mvn clean test
#
#      - name: Deploy pages
#        uses: JamesIves/github-pages-deploy-action@v4.5.0
#        with:
#          branch: gh-pages
#          folder: ./reports

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use your Java version (e.g., 8, 11, etc.)

      - name: Set up Xvfb (Virtual Display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 &  # Start virtual display

      - name: Run Tests in Headless Mode
        run: |
          mvn clean test -Djava.awt.headless=true  # Run Maven tests in headless mode

      - name: Upload Extent Report (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: extent-report
          path: target/extent-report.html  # Specify the location of your report
