            - name: allure-html-reporter-github-pages
  # You may pin to the exact commit or the version.
  # uses: PavanMudigonda/allure-html-reporter-github-pages@494af460cf5d0c0a0a4e48f800fc3fe48891cf21
  uses: PavanMudigonda/allure-html-reporter-github-pages@v1.2
  with:
    # ALLURE RESULTS JSON FILE

    ALLURE_RESULTS_JSON: # optional, default is ./
    # Workflow File NAME
    WORKFLOW_ID: # default is 
    # Github Token
    token: # default is ${{ github.token }}
    # Test Environment
    test_env: # default is QA
    # Allure test result data dir
    allure_results: # default is allure-results
    # Allure report target dir
    allure_report: # default is allure-report
    # Folder with gh-pages branch
    gh_pages: # default is gh-pages
    # Folder for allure history
    allure_history: # default is allure-history
    # subfolder
    subfolder: # optional, default is 
    # Keep X last reports
    keep_reports: # optional, default is 20
    # GitHub Actions build number
    github_run_num: # default is ${{ github.run_number }}
    # GitHub Actions run id
    github_run_id: # default is ${{ github.run_id }}
    # GitHub repository
    github_repo: # default is ${{ github.repository }}
    # GitHub repository owner
    github_repo_owner: # default is ${{ github.repository_owner }}
    # Use a custom URL instead of *.github.io
    report_url: # optional, default is 
          
