name: Run Selenium Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17 (or your required Java version)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step to set up Chrome and Chromedriver (Correct action)
      - name: Set up ChromeDriver
        uses: browser-actions/setup-chrome-driver@v1
        with:
          chromedriver-version: 'latest'  # Ensure this matches the version you want

      # Run Maven to execute the tests
      - name: Run Maven tests
        run: mvn clean test

      # Generate and serve Allure report
      - name: Generate Allure report
        run: mvn allure:serve

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin





#name: Run tests and publish report
#on: [push]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: zulu
#          java-version: 17
#
#      - name: Run tests in headless mode
#        run: |
#          mvn clean test -Djava.awt.headless=true -X
#
#      - name: Check test results
#        run: ls -al target/surefire-reports  # Verify test result files are generated
