name: Run Selenium Tests with Allure Report and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to 'master' branch
  pull_request:
    branches:
      - master  # Trigger on PR to 'master' branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner (or change as needed)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        ./mvnw install  # Run your Maven install

    - name: Run Selenium Tests
      run: |
        ./mvnw test  # Run your Selenium tests

    - name: Generate Allure Report
      run: |
        mvn allure:report  # Generate the Allure report

    - name: Move Report to docs Folder
      run: |
        mkdir -p docs  # Create the 'docs' folder if not exists
        mv target/allure-report docs/  # Move the Allure report to 'docs/'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for deployment
        publish_dir: ./docs/allure-report  # Directory containing the Allure report
        publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
