name: Run Selenium Tests with Allure Report and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to 'master' branch
  pull_request:
    branches:
      - master  # Trigger the workflow on PRs to 'master' branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner (or change as needed)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Specify the Java version
        distribution: 'adopt'  # Optional, specify the OpenJDK distribution

    - name: Install SafariDriver
      run: |
        sudo safaridriver --enable

    - name: Build with Maven
      run: mvn clean install  # Use `gradle build` if you are using Gradle

    - name: Run Tests
      run: mvn test  # Use `gradle test` if you are using Gradle
      
    - name: Generate Allure Report
      run: |
        mvn allure:report  # Generate Allure report using Maven
        mkdir -p docs  # Ensure the docs folder exists
        mv target/allure-report docs/  # Move Allure report to 'docs' folder

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for deployment
        publish_dir: ./docs/allure-report  # Directory containing the Allure report
        publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
