name: Run Selenium Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to 'master' branch
  pull_request:
    branches:
      - master  # Trigger the workflow when PRs are opened/updated for the 'master' branch

jobs:
  build:
    runs-on: macos-latest  # Use the macOS environment for the CI build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Specify the Java version you want to use
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        ./mvnw install  # Adjust this if you're using another build tool (e.g., Maven, Gradle)

    - name: Run Selenium Tests
      run: |
        ./mvnw test  # Run your Selenium tests (adjust the command if needed)

    - name: Generate Report
      run: |
        mkdir -p docs  # Create a directory for storing the HTML report
        mv target/extent-report.html docs/  # Move the generated report into the 'docs' folder

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token provided by default
        publish_dir: ./docs  # The directory containing the HTML report
        publish_branch: gh-pages  # The branch to publish to for GitHub Pages
